### ISSUE TITLE
Client Crashes when jumping into river

### ISSUE THREAD

**Issue by tanknet** [AllTheMods/ATM-6#111]
ATM6 Version: 1.0.1  Minecraft Version: 1.16.2  (modded) forge-33.0.32

Playing on Multiplayer Server

Client crashes when jumping into water.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/5/20 1:43 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidUtil.getFluidContained(Lnet/minecraft/item/ItemStack;)Lnet/minecraftforge/common/util/LazyOptional;
	at mcjty.theoneprobe.apiimpl.providers.DefaultProbeInfoProvider.showStandardBlockInfo(DefaultProbeInfoProvider.java:279) ~[?:1.16-3.0.4-beta] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.getWaitingInfo(OverlayRenderer.java:298) ~[?:1.16-3.0.4-beta] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:263) ~[?:1.16-3.0.4-beta] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:115) ~[?:1.16-3.0.4-beta] {re:classloading}
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110) ~[?:1.16-3.0.4-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_736_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:471) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.32.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$473/65838989.call(Unknown Source) [forge-1.16.2-33.0.32.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcjty.theoneprobe.apiimpl.providers.DefaultProbeInfoProvider.showStandardBlockInfo(DefaultProbeInfoProvider.java:279)
	at mcjty.theoneprobe.rendering.OverlayRenderer.getWaitingInfo(OverlayRenderer.java:298)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:263)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:115)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110)
	at net.minecraftforge.eventbus.ASMEventHandler_736_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['tanknet'/97406, l='ClientLevel', x=2857.54, y=62.19, z=729.07]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (3434,65,-887), Chunk: (at 10,4,9 in 214,-56; contains blocks 3424,0,-896 to 3439,255,-881), Region: (6,-2; contains chunks 192,-64 to 223,-33, blocks 3072,0,-1024 to 3583,255,-513)
	Level time: 1632579 game time, 1712690 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:605)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$473/65838989.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412826896 bytes (393 MB) / 2396487680 bytes (2285 MB) up to 6944456704 bytes (6622 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6656m -Xms256m -XX:PermSize=256m -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.32.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.32
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		NetherPortalFix_1.16.2-7.1.0.jar NetherPortalFix {netherportalfix@7.1.0 DONE}
		aiotbotania-1.16.2-1.3.1.jar AIOT Botania {aiotbotania@1.3.1 DONE}
		simplemagnets-1.0.6-mc1.16.2.jar Simple Magnets {simplemagnets@1.0.6 DONE}
		mcw-windows-1.0.2-mc1.16.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		modnametooltip_1.16.2-1.15.0.jar Mod Name Tooltip {modnametooltip@1.15.0 DONE}
		rsgauges-1.16.2-1.2.4-b6.jar Gauges and Switches {rsgauges@1.2.4-b6 DONE}
		IronJetpacks-1.16.2-4.1.0.jar Iron Jetpacks {ironjetpacks@4.1.0 DONE}
		ForgeEndertech-1.16.2-7.0.2.0-build.0012.jar Forge Endertech {forgeendertech@7.0.2.0 DONE}
		CookingForBlockheads_1.16.2-9.1.1.jar Cooking for Blockheads {cookingforblockheads@9.1.1 DONE}
		Controlling-7.0.0.4.jar Controlling {controlling@7.0.0.4 DONE}
		ReAuth-1.16-Forge-3.9.1.jar ReAuth {reauth@3.9.1 DONE}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 DONE}
		dankstorage-3.10a.jar Dank Storage {dankstorage@3.10a DONE}
		citadel-1.3.0.jar Citadel {citadel@1.3.0 DONE}
		ftb-gui-library-1.0.0.18.jar FTB GUI Library {ftbguilibrary@1.0.0.18 DONE}
		rangedpumps-0.8.1.jar Ranged Pumps {rangedpumps@0.8.1 DONE}
		potionsmaster-0.1.16-1.16.2-33.0.32.jar Potions Master {potionsmaster@0.1.16 DONE}
		WitherSkeletonTweaks-1.16.2-5.1.0.jar Wither Skeleton Tweaks {wstweaks@5.1.0 DONE}
		Bookshelf-1.16.2-7.0.7.jar Bookshelf {bookshelf@7.0.7 DONE}
		u_team_core-1.16.2-3.1.7.178.jar U Team Core {uteamcore@3.1.7.178 DONE}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 DONE}
		Apotheosis-1.16.2-4.2.1.jar Apotheosis {apotheosis@4.2.1 DONE}
		mcw-doors-1.0.0-mc1.16.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		LightingWand-1.16.2-1.7.0.jar Lighting Wand {lightingwand@1.7.0 DONE}
		Morpheus-1.16.2-4.2.58.jar Morpheus {morpheus@version DONE}
		Ma-Essentials-1.16.2-3.3.0.jar Ma Essentials {maessentials@1.16.2-3.3.0 DONE}
		ftb-teams-1.0.1.12.jar FTB Teams {ftbteams@1.0.1.12 DONE}
		shetiphiancore-1.16-3.8.1.jar ShetiPhian-Core {shetiphiancore@3.8.1 DONE}
		absentbydesign-1.16.2-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.2-1.1.0 DONE}
		refinedstorage-1.9.4.jar Refined Storage {refinedstorage@1.9.4 DONE}
		PackMenu-1.16.2-2.2.0.jar Pack Menu {packmenu@2.2.0 DONE}
		alltheores-0.1.1-1.16.2-33.0.32.jar AllTheOres {alltheores@0.1.1 DONE}
		mcw-bridges-1.0.4-mc1.16.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.16.2-1.11.4.79.jar Useful Backpacks {usefulbackpacks@1.11.4.79 DONE}
		torchmaster-2.3.3-alpha.jar Torchmaster {torchmaster@2.3.3-alpha DONE}
		crashutilities-3.4.jar Crash Utilities {crashutilities@3.4 DONE}
		Compressium-1.0.27.jar Compressium {compressium@1.16.2-1.0.4 DONE}
		AdPoles-1.16.2-5.0.1.0-build.0012.jar To the Bat Poles! {adpoles@5.0.1.0 DONE}
		valkyrielib-1.16.2-3.0.3.1.jar ValkyrieLib {valkyrielib@1.16.2-3.0.3.1 DONE}
		ftb-ranks-1.0.0.7.jar FTB Ranks {ftbranks@1.0.0.7 DONE}
		simplylight-1.16.2-1.0.2.jar Simply Light {simplylight@1.16.2-1.0.2 DONE}
		tgcropesmod-1.16.2-1.1.0.jar Ropes Mod {tgcropesmod@1.16.2-1.1.0 DONE}
		atmadditions-1.16.2-1.0.0.jar All The Mods: Additions {atmadditions@1.16.2-1.0.0 DONE}
		curios-forge-1.16.2-4.0.0.1.jar Curios API {curios@1.16.2-4.0.0.1 DONE}
		Botania-1.16.2-405.jar Botania {botania@1.16.2-405 DONE}
		Patchouli-1.16-42.jar Patchouli {patchouli@1.16-42 DONE}
		collective-1.16.2-1.39.jar Collective {collective@1.39 DONE}
		camera-1.16.2-1.0.4.jar Camera Mod {camera@1.16.2-1.0.4 DONE}
		elevatorid-1.16.2-1.7.4.jar Elevator Mod {elevatorid@1.16.2-1.7.4 DONE}
		ftb-ultimine-1.1.0.10.jar FTB Ultimine {ftbultimine@1.1.0.10 DONE}
		constructionwand-1.16.2-1.2.jar Construction Wand {constructionwand@1.16.2-1.2 DONE}
		mcws-roofs-1.16.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		cc-tweaked-1.16.2-1.91.0.jar CC: Tweaked {computercraft@1.91.0 DONE}
		Better Muffling-1.16.2-1.0.1.jar Better Muffling {bettermuffling@1.0.1 DONE}
		cloth-config-forge-4.1.0.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		trashcans-1.0.3-mc1.16.2.jar Trash Cans {trashcans@1.0.3 DONE}
		tramplestopper-1.16.2-2.0.0.2-universal.jar Trample Stopper {tramplestopper@1.16.2-2.0.0.2-universal DONE}
		bwncr-1.16.2-3.8.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.2-3.8.15 DONE}
		BetterAdvancements-1.16.2-0.1.0.101.jar Better Advancements {betteradvancements@0.1.0.101 DONE}
		Cucumber-1.16.2-4.1.1.jar Cucumber Library {cucumber@4.1.1 DONE}
		TrashSlot_1.16.2-12.1.0.jar TrashSlot {trashslot@12.1.0 DONE}
		mining-helmet-1.16.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		woot-1.16.2-1.0.0.0.jar Woot {woot@1.16.2-1.0.0.0 DONE}
		platforms-1.16-1.7.2b.jar Platforms {platforms@1.7.2 DONE}
		jei-1.16.2-7.3.2.25.jar Just Enough Items {jei@7.3.2.25 DONE}
		kubejs-2.8.0.63.jar KubeJS {kubejs@2.8.0.63 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		Clumps-6.0.0.9.jar Clumps {clumps@6.0.0.9 DONE}
		light-overlay-5.5.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		enviromats-1.16.2-2.0.3.0.jar Environmental Materials {enviromats@1.16.2-2.0.3.0 DONE}
		comforts-forge-1.16.2-4.0.0.0.jar Comforts {comforts@1.16.2-4.0.0.0 DONE}
		appliedenergistics2-8.1.0-alpha.1.jar Applied Energistics 2 {appliedenergistics2@8.1.0-alpha.1 DONE}
		NaturesCompass-1.16.2-1.8.5.jar Nature's Compass {naturescompass@1.16.2-1.8.5 DONE}
		DimStorage-1.16.2-4.1.0.jar DimStorage {dimstorage@4.1.0 DONE}
		engineerstools-1.16.2-1.1.0-b3.jar Engineer's Tools {engineerstools@1.1.0-b3 DONE}
		FarmingForBlockheads_1.16.2-7.1.1.jar Farming for Blockheads {farmingforblockheads@7.1.1 DONE}
		mcjtylib-1.16-5.0.4.jar McJtyLib {mcjtylib@1.16-5.0.4 DONE}
		rftoolsbase-1.16-2.0.3-beta.jar RFToolsBase {rftoolsbase@1.16-2.0.3-beta DONE}
		xnet-1.16-3.0.3-beta.jar XNet {xnet@1.16-3.0.3-beta DONE}
		rftoolsstorage-1.16-2.0.3-beta.jar RFToolsStorage {rftoolsstorage@1.16-2.0.3-beta DONE}
		rftoolscontrol-1.16-4.0.3-beta.jar RFToolsControl {rftoolscontrol@1.16-4.0.3-beta DONE}
		restrictions-1.16-3.0.1-beta.jar Restrictions {restrictions@1.16-3.0.1-beta DONE}
		mahoutsukai-1.16.2-v1.22.1.jar Mahou Tsukai {mahoutsukai@1.16.2-v1.22.1 DONE}
		ToastControl-1.16.2-4.2.0.jar Toast Control {toastcontrol@4.2.0 DONE}
		mininggadgets-1.5.0.jar Mining Gadgets {mininggadgets@1.5.0 DONE}
		rftoolspower-1.16-3.0.4-beta.jar RFToolsPower {rftoolspower@1.16-3.0.4-beta DONE}
		extradisks-1.16.2-1.3.1.jar Extra Disks {extradisks@1.3.1 DONE}
		ftb-chunks-1.1.1.32.jar FTB Chunks {ftbchunks@1.1.1.32 DONE}
		forge-1.16.2-33.0.32-universal.jar Forge {forge@33.0.32 DONE}
		ironchest-1.16.2-11.1.5.jar Iron Chests {ironchest@1.16.2-11.1.5 DONE}
		CraftingTweaks_1.16.2-12.1.1.jar Crafting Tweaks {craftingtweaks@12.1.1 DONE}
		forge-1.16.2-33.0.32-client.jar Minecraft {minecraft@1.16.2 DONE}
		rftoolsutility-1.16-3.0.6-beta.jar RFToolsUtility {rftoolsutility@1.16-3.0.6-beta DONE}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta DONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.2-1.14.4.jar Tool Belt {toolbelt@1.14.4 DONE}
		useful_railroads-1.16.2-1.4.3.28.jar Useful Railroads {usefulrailroads@1.4.3.28 DONE}
		allthemodium-1.0.8-1.16.2-33.0.32.jar Allthemodium {allthemodium@1.0.8 DONE}
		rftoolsbuilder-1.16-3.0.3-beta.jar RFToolsBuilder {rftoolsbuilder@1.16-3.0.3-beta DONE}
		pamhc2foodcore-1.16.2-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.16.2-1.0.5.jar Gravestone Mod {gravestone@1.16.2-1.0.5 DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		FastWorkbench-1.16.2-4.3.0.jar FastWorkbench {fastbench@4.3.0 DONE}
		polymorph-forge-1.16.2-0.14.jar Polymorph {polymorph@1.16.2-0.14 DONE}
		AutoRegLib-1.6-45.jar AutoRegLib {autoreglib@1.6-45 DONE}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 DONE}
		FastFurnace-1.16.2-4.2.0.jar FastFurnace {fastfurnace@4.2.0 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.2-1.1.2-b4.jar Engineer's Decor {engineersdecor@1.1.2-b4 DONE}
		allthetweaks-1.0.2-1.16.2-33.0.32.jar All The Tweaks {allthetweaks@1.0.2 DONE}
		byg-1.0.4.jar Oh The Biomes You'll Go {byg@1.0.4 DONE}
		refinedstorageaddons-0.7.1.jar Refined Storage Addons {refinedstorageaddons@0.7.1 DONE}
		CosmeticArmorReworked-1.16.2-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.2-v1 DONE}
		xptome-1.16.2-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
		DefaultOptions_1.16.2-12.1.1.jar Default Options {defaultoptions@12.1.1 DONE}
	Patchouli open book context: n/a
	Launched Version: forge-33.0.32
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by WhitePhant0m** [comment]
Next time please post your crash log to https://pastebin.com/
But, have you tested if it crashes on 1.0.2?

**Comment by tanknet** [comment]
Thanks will remember in future.

Upgraded and no client crashes in or around water
