### ISSUE TITLE
Mob masher from Mob Grinding Utils causes server crash if player stands on top

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1324]
v.1.5.7

1) Stand on the masher from Mob Grinding Utils.
2) Watch the world go down with you.

[02.04 12:35:39] [Server] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
[02.04 12:35:39] [Server] net.minecraft.crash.ReportedExceptionTicking block entity
[02.04 12:35:39] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
[02.04 12:35:39] [Server] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[02.04 12:35:39] [Server] Caused byjava.lang.NullPointerException
[02.04 12:35:39] [Server] 	at net.minecraft.entity.player.ServerPlayerEntity.func_70670_a(ServerPlayerEntity.java:1114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
[02.04 12:35:39] [Server] 	at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntity.java:825) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.onHit(FrostRebukeEnchantment.java:92) ~[ensorcellation:1.2.{re:classloading}
[02.04 12:35:39] [Server] 	at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.func_151367_b(FrostRebukeEnchantment.java:72) ~[ensorcellation:1.2.{re:classloading}
[02.04 12:35:39] [Server] 	at net.minecraft.enchantment.EnchantmentHelper.func_212575_b(EnchantmentHelper.java:141) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
[02.04 12:35:39] [Server] 	at net.minecraft.enchantment.EnchantmentHelper.func_222184_a(EnchantmentHelper.java:104) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
[02.04 12:35:39] [Server] 	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_{}
[02.04 12:35:39] [Server] 	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:103) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
[02.04 12:35:39] [Server] 	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:113) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
[02.04 12:35:39] [Server] 	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:144) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
[02.04 12:35:39] [Server] 	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1152) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
[02.04 12:35:39] [Server] 	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:101) ~[mob_grinding_utils:1.16.5-0.4.{re:classloading}
[02.04 12:35:39] [Server] 	at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:66) ~[mob_grinding_utils:1.16.5-0.4.{re:classloading}
[02.04 12:35:39] [Server] 	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
[02.04 12:35:39] [Server] 	... more

**Comment by Pdiddy973** [comment]
Please use pastebin or a gist for logs

**Comment by jeremiahwinsley** [comment]
Fixed in 1.5.8.
