### ISSUE TITLE
Creative centrifuge corrupts a chunk and make all clients crash

### ISSUE THREAD

**Issue by pokermanx** [AllTheMods/ATM-6#1325]
v.1.5.7

[29Mar2021 03:29:57.354] [Server thread/ERROR] [net.minecraft.world.chunk.Chunk/]: A TileEntity type com.YTrollman.CentrifugeTiers.tileentity.CentrifugeCasingTileEntityTierCreative has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: null

repeats like forever

client results crashing with code 0 so there are no client side logs, last thing logged that may be helpful

java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:184) ~[?:7.6.1.75]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:87) ~[?:7.6.1.75]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[?:7.6.1.75]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[?:7.6.1.75]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[?:7.6.1.75]
	at mezz.jei.recipes.RecipeManager.addRecipe(RecipeManager.java:143) [?:7.6.1.75]
	at mezz.jei.recipes.RecipeManager.addRecipeTyped(RecipeManager.java:105) [?:7.6.1.75]
	at mezz.jei.recipes.RecipeManager.addRecipes(RecipeManager.java:98) [?:7.6.1.75]
	at mezz.jei.recipes.RecipeManager.<init>(RecipeManager.java:90) [?:7.6.1.75]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:142) [?:7.6.1.75]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [?:7.6.1.75]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:141) [?:7.6.1.75]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:134) [?:7.6.1.75]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:100) [?:7.6.1.75]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$30507/577838585.accept(Unknown Source) [?:7.6.1.75]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2946/1398063054.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2585/1993217890.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.lambda$handle$2(FMLPlayMessages.java:426) [?:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes$$Lambda$32596/2100850401.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) [?:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.handle(FMLPlayMessages.java:405) [?:?]
	at net.minecraftforge.fml.network.NetworkInitialization$$Lambda$3003/1657936637.accept(Unknown Source) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$31439/1263924782.accept(Unknown Source) [?:?]
	at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2944/754346482.accept(Unknown Source) [?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2946/1398063054.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2585/1993217890.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$31427/1525234804.apply(Unknown Source) [?:?]
	at java.util.Optional.map(Optional.java:215) [?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$31866/1024111909.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.2.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$485/1886878309.call(Unknown Source) [forge-1.16.5-36.1.2.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by Pdiddy973** [comment]
Please use pastebin for logs, try and update Ctiers should fix that

**Comment by pokermanx** [comment]
Yeah, sorry, was a bit lazy, update should be global or serverside/cliendside only?

**Comment by Pdiddy973** [comment]
> Yeah, sorry, was a bit lazy, update should be global or serverside/cliendside only?

Both server/client
