### ISSUE TITLE
The game crashes after reloading the world (All the Mods 6-1.6.4)

### ISSUE THREAD

**Issue by Keltas** [AllTheMods/ATM-6#1690]
<All the Mods 6-1.6.4>

**Describe the bug**
Once you exit the game from a world back to main menu, entering back in (or creating a new world) results in crash.

**To Reproduce**
1. Enter a world (or create a new one).
2. Exit the world to main menu.
3. Enter a world (or create a new one).
4. The game crashes.

**Logs**
crash log:
https://pastebin.com/EXNJmMYs
latest log:
https://paste.ubuntu.com/p/zYwXTNwcXd/

**Comment by Ajhplyr** [comment]
Hello,

I have the same problème with my server.
We are four to play on this server but we can no more play at the same time with this error.

Each connexion after the first led to an "internal server error".
There seems to be an NullPointerException from FTBEssentials juste after the building of the quest package.

For @Keltas, check at 13:06:28

For me, here is the error log that I have :
```
[24May2021 18:07:17.211] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Ajhplyr joined the game
[24May2021 18:07:17.444] [Server thread/DEBUG] [Silent Gear/]: Sending materials crafting item correction packet
[24May2021 18:07:17.445] [Server thread/DEBUG] [Silent Gear/]: Sending parts crafting item correction packet
[24May2021 18:07:17.447] [Server thread/DEBUG] [FTB Quests/]: Wrote 15423 bytes, 247 objects
[24May2021 18:07:17.450] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 8
	Listeners:
		0: HIGHEST
		1: ASM: class net.silentchaos512.gear.event.ServerEvents onPlayerJoinServer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: ASM: io.github.noeppi_noeppi.libx.impl.config.ConfigEvents@538ab4c6 playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: HIGH
		4: ASM: class ovh.corail.tombstone.event.EventHandler onPlayerLogued(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: NORMAL
		7: ASM: class com.supermartijn642.configlib.ConfigLib$ConfigEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: class com.feed_the_beast.mods.ftbessentials.FTBEEventHandler playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: ASM: class net.gigabit101.shrink.events.PlayerEvents playerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: ASM: class xreliquary.handler.CommonEventHandler blameDrullkus(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		12: ASM: mods.waterstrainer.event.EventPlayerLoggedIn@232f388e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class net.silentchaos512.gear.util.GearData$EventHandler onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: class net.blay09.mods.farmingforblockheads.registry.market.MarketRegistryLoader onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: class me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager$EventListener serverLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: ASM: class com.logprot.event.EventHandler onEntityAdded(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		17: ASM: org.cyclops.integrateddynamics.core.persist.world.LabelsWorldStorage@5a02618d onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: class blusunrize.immersiveengineering.common.blocks.multiblocks.StaticTemplateManager onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		20: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		21: ASM: class com.leobeliik.extremesoundmuffler.eventHandlers.PlayerEventsHandler onPlayerLoggin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: ASM: class hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		23: ASM: net.minecraftforge.common.ForgeInternalHandler@7970fde7 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: class vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: ASM: class vazkii.psi.common.core.handler.LoopcastTrackingHandler onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		26: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		27: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		28: ASM: com.valkyrieofnight.envirotech.m_voidminer.datapack.voidregistry.VoidMinerDataRegistry@7c7970fd onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		29: ASM: com.valkyrieofnight.envirotech.m_voidminer.datapack.program.VoidMinerProgramRegistry@50406b14 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		30: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@1c19802f
		31: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@239b8ef
		32: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		33: ASM: com.valkyrieofnight.envirocore.m_machines.m_lens_grinder.dp.cat.LensGrinderCategoryRegistry@4d3f3062 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		34: ASM: com.valkyrieofnight.envirocore.m_machines.m_lens_grinder.dp.LensGrinderRecipeRegistry@6df717fb onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		35: ASM: com.valkyrieofnight.envirocore.m_machines.m_mem_progrm.datapack.cat.MemProgrmCategoryRegistry@7cc1c46e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		36: ASM: com.valkyrieofnight.envirocore.m_machines.m_mem_progrm.datapack.MemProgrmRecipeRegistry@79bb9715 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		37: ASM: com.valkyrieofnight.envirocore.m_machines.m_assembler.datapack.AssemblerRecipeRegistry@3678dbe9 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		38: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		39: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		40: ASM: net.blay09.mods.trashslot.TrashSlot@7ea3c25b onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		41: ASM: class sirttas.elementalcraft.entity.EntityHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		42: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		43: ASM: de.castcrafter.travel_anchors.EventListener@63af0ddc playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		44: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@229f0140
		45: ASM: stepsword.mahoutsukai.handlers.ServerHandler@19e9d7f5 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		46: ASM: com.feed_the_beast.mods.ftbchunks.FTBChunks@69d42384 loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		47: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@5b8c8b54
		48: ASM: class slimeknights.tconstruct.shared.PlayerDataEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		49: ASM: class com.ma.progression.ProgressionEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		50: ASM: class sonar.fluxnetworks.register.CommonEventHandler onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		51: ASM: class com.minecolonies.coremod.event.EventHandler onPlayerEnterWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		52: ASM: class com.minecolonies.coremod.event.FMLEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		53: ASM: class com.cazsius.solcarrot.tracking.MaxHealthHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		54: ASM: class com.cazsius.solcarrot.tracking.CapabilityHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		55: ASM: class vazkii.quark.base.handler.ContributorRewardHandler onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		56: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@bc470f2
		57: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@7eab925c onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		58: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@16b76207 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		59: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@24de031e onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		60: ASM: shadows.apotheosis.ench.EnchModuleEvents@59222f61 login(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		61: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@44755fa5
		62: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@1e3ad36a
		63: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@338335fd playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		64: ASM: mekanism.common.CommonPlayerTracker@7862ef22 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		65: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@3e15c78d onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		66: ASM: mcjty.theoneprobe.ForgeEventHandlers@5c65142e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		67: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@2bfe4b9b onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		68: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@2b854898 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		69: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@21532dd2
		70: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@5abdcb37 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		71: ASM: squeek.appleskin.network.SyncHandler@4c39ea68 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		72: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@9b89aea
		73: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@38364f26 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		74: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@30db72b5 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		75: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@4f07ae54 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		76: ASM: edivad.dimstorage.manager.DimStorageManager$DimStorageSaveHandler@2fdcb35c onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		77: net.minecraftforge.eventbus.EventBus$$Lambda$2840/0x0000000800de7040@675e640f
		78: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@586d0580 joinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		79: ASM: mob_grinding_utils.events.ChickenFuseEvent@4b18ae7 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		80: LOWEST
		81: ASM: shetiphian.core.internal.modintegration.ftbteams.FTBTeams_Active$FTBEventHandler@4d44bb74 playerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
	at com.feed_the_beast.mods.ftbessentials.net.UpdateTabNamePacket.write(UpdateTabNamePacket.java:41)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147)
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85)
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98)
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129)
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:124)
	at com.feed_the_beast.mods.ftbessentials.util.FTBEPlayerData.sendTabName(FTBEPlayerData.java:251)
	at com.feed_the_beast.mods.ftbessentials.FTBEEventHandler.playerLoggedIn(FTBEEventHandler.java:108)
	at net.minecraftforge.eventbus.ASMEventHandler_15_FTBEEventHandler_playerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Unknown Source)

[24May2021 18:07:17.452] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /91.171.49.31:56475
java.lang.NullPointerException: null
	at com.feed_the_beast.mods.ftbessentials.net.UpdateTabNamePacket.write(UpdateTabNamePacket.java:41) ~[ftbessentials:1604.1.0.13]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[forge:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:124) ~[forge:?]
	at com.feed_the_beast.mods.ftbessentials.util.FTBEPlayerData.sendTabName(FTBEPlayerData.java:251) ~[ftbessentials:1604.1.0.13]
	at com.feed_the_beast.mods.ftbessentials.FTBEEventHandler.playerLoggedIn(FTBEEventHandler.java:108) ~[ftbessentials:1604.1.0.13]
	at net.minecraftforge.eventbus.ASMEventHandler_15_FTBEEventHandler_playerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[24May2021 18:07:20.686] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Ajhplyr lost connection: Internal server error
[24May2021 18:07:20.687] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Ajhplyr left the game
```

Regards

**Comment by radiomike** [comment]
These crashes are not related to each other in any way.

@Keltas try updating your java to latest java8 or java11. 

@Ajhplyr you should probably start a new bug report for this. However, it's likely yours is to do with nicknames via ftb essentials. You may be able to solve it by editing or deleting players json files from `<world>/ftbessentials/playerdata` Probably best to do this when server is off. If this doesn't work, do create a new bug report here, and check out the discord.

**Comment by Keltas** [comment]
I've just learned that Curseforge has its own Java separate from the system one (which is up-to-date). I've changed the Curseforge settings to use my newest Java, but it still uses its own old one. I've even deleted it from Curseforge folder, but it gets redownloaded when I start Minecraft. Even if I create a new instance it still uses the old version.

**Comment by Ajhplyr** [comment]
@radiomike Thanks for your reply. I will create another bug repport and check the discord as you proposed.

**Comment by Keltas** [comment]
Ok. So it is Minecraft that has a default Java version. Changing the profile options in the launcher has finally allowed me to start Minecraft with up-to date Java. I still however get the crash. Here are the logs:
Crashlog: https://pastebin.com/zGSyhkNg
Latest: https://paste.ubuntu.com/p/gd4hHnR5RD/

**Comment by radiomike** [comment]
Just done some testing myself, looks like an interaction between Pneumaticraft and Minecolonies. Have submitted a bug report with Pneumaticraft for now, see https://github.com/TeamPneumatic/pnc-repressurized/issues/811

**Comment by radiomike** [comment]
This should be fixed in latest version of pneumaticraft.
