### ISSUE TITLE
Modpack Version 1.6.8 is crashing on startup

### ISSUE THREAD

**Issue by RefugeeOfVietnam** [AllTheMods/ATM-6#1774]
**Describe the bug**
When starting All The Mods 6 from CurseForge launcher it crashes on startup when i press play in Minecraft Launcher. This has only happened when I updated All The Mods 6 to 1.6.8 and have tried everything from re-installing Minecraft to deleting All The Mods 6 multiple times. 

**To Reproduce**
1. Go to 'CurseForge Launcher'
2. Click on 'All The Mods 6 -> Play'
3. Takes you to Minecraft Launcher
4. Click on edit "All The Mods 6" Profile
5.  Consolidated Ram. Mine was 4096 then changed it to 8096
6. Clicked on play then takes me to loading screen
7. I then get "Exit Code: 0"

**Screenshots**
![Screenshot (50)](https://user-images.githubusercontent.com/85660443/121461707-38b17a80-c964-11eb-887c-99bb1f68f6ec.png)

**Logs**
[20:48:56] [main/INFO]: ModLauncher running: args [--username, RefugeeOfVietnam, --version, forge-36.1.25, --gameDir, C:\Users\Austin\curseforge\minecraft\Instances\All the Mods 6 - ATM6 - 1.16.5, --assetsDir, C:\Users\Austin\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, 1a02d52fc1484fdc96bbcbf9ee68eb4b, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.25, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[20:48:56] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[20:48:56] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[20:48:57] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[20:48:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Austin/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[20:48:58] [main/WARN]: File C:\Users\Austin\curseforge\minecraft\Install\libraries\net\minecraftforge\forge\1.16.5-36.1.25\forge-1.16.5-36.1.25-universal.jar has been ignored - it is invalid
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.ModSorter.buildUniqueList(ModSorter.java:188)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:64)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:129)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:216)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:114)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$182/2035616217.apply(Unknown Source)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[20:48:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by ladylexxie** [comment]
Exit Code 0 is from the launcher, not from Minecraft.
We need you to upload the full logs to pastebin or other text sharing website.

**Comment by RefugeeOfVietnam** [comment]
https://pastebin.com/eAcbUgfp

**Comment by ladylexxie** [comment]
If that is the whole log, there's something wrong with your install. Try GD Launcher instead of CF, since CF is a very shit launcher and causes issues.

**Comment by RefugeeOfVietnam** [comment]
The pastebin above is the one that I got from when I posted this issue. The one below is the most recent log I got and here is an image of when it is attempting to load the game. 
https://pastebin.com/3aEhiVsR
![Screenshot (53)](https://user-images.githubusercontent.com/85660443/121604821-19682b00-ca00-11eb-9b44-96b0c55539bd.png)

**Comment by RefugeeOfVietnam** [comment]
I honestly don't understand what specifically is wrong or what the issue is. But the only thing I can say is that I haven't touched any of the files, the only thing I change which I always did for the previous version was allocate RAM. Besides that I have uninstalled and download the mod pack multiple times as well as the backups with no luck.

**Comment by ladylexxie** [comment]
It appears that the forge version CF downloaded is invalid:
`forge-1.16.5-36.1.25-universal.jar has been ignored - it is invalid`
which is most likely caused by CF.

**Comment by RefugeeOfVietnam** [comment]
What is GD?

**Comment by ladylexxie** [comment]
GDLauncher is what we recommend people use for Minecraft modpacks. We always recommend people stay away from the mess that is CurseForge.
https://gdevs.io

**Comment by RefugeeOfVietnam** [comment]
Ok I'll try that and come back if I have any issues. Thank you btw!

**Comment by RefugeeOfVietnam** [comment]
It is working now, and Im able to load onto the start menu thank you btw, and sorry for my stupidity. lol

**Comment by ladylexxie** [comment]
You're welcome! Nothing to be sorry for :P
Enjoy!
