### ISSUE TITLE
invalid dist DEDICATED_SERVER for 1.7.6 server

### ISSUE THREAD

**Issue by Kenton-bruh** [AllTheMods/ATM-6#2132]
[10:35:16] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@466d7187
[10:35:16] [Server thread/ERROR] [co.lo.cy.ModCyclic/]: C PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
[10:35:16] [Server thread/INFO] [minecraft/PlayerList]: 1Kenton[/127.0.0.1:14034] logged in with entity id 1148 at (-31.411844633543712, 72.0, 70.61063617545233)
[10:35:16] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[10:35:16] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /127.0.0.1:14034
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.2.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        at jeresources.profiling.ProfileCommand.lambda$register$0(ProfileCommand.java:26) ~[jeresources:0.12.1.127] {re:classloading}
        at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.lambda$test$0(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading}
        at dev.ftb.mods.ftbranks.api.OptionalBoolean.orElseGet(OptionalBoolean.java:58) ~[ftbranks:?] {re:classloading}
        at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading}
        at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:15) ~[ftbranks:?] {re:classloading}
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?] {re:classloading}
        at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:597) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:162) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}
[10:35:19] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: 1Kenton lost connection: Internal server error

**Comment by Kenton-bruh** [comment]
it says modlauncher-8.0.9.jar is the problem but its not in mods folder and in a different folder and I deleted it and same thing happened

**Comment by radiomike** [comment]
Seems to be an issue with the current just enough resources on the server. Try deleting that mod from your server.

**Comment by Kenton-bruh** [comment]
Thank you that worked!
