### ISSUE TITLE
Internal Server Error with the version 1.7.7

### ISSUE THREAD

**Issue by NikeeyGH** [AllTheMods/ATM-6#2139]
I tried to log in on my Server but i can´t even join.

This is the report from the console.

[20:37:45] [User Authenticator #7/INFO] [minecraft/ServerLoginNetHandler]: UUID of player NikeeyDE is 83c45f47-9e81-4537-abfd-25b8e7b3853a
[20:38:10] [Server thread/ERROR] [co.lo.cy.ModCyclic/]: ? overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
[20:38:10] [Server thread/ERROR] [co.lo.cy.ModCyclic/]: C PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]} [20:38:10] [Server thread/INFO] [minecraft/PlayerList]: NikeeyDE[/84.118.129.57:55566] logged in with entity id 2733 at (862.4224801601271, 64.0, 1064.2558136391112)
[20:38:10] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[20:38:10] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /84.118.129.57:55566 java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.2] {} at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {} at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {} at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {} at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading} at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading} at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] {} at jeresources.profiling.ProfileCommand.lambda$register$0(ProfileCommand.java:26) ~[jeresources:0.12.1.127] {re:classloading} at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.lambda$test$0(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading} at dev.ftb.mods.ftbranks.api.OptionalBoolean.orElseGet(OptionalBoolean.java:58) ~[ftbranks:?] {re:classloading} at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading} at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:15) ~[ftbranks:?] {re:classloading} at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?] {re:classloading} at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:ftbranks-common.mixins.json:CommandsMixin,pl:mixin:A} at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:ftbranks-common.mixins.json:CommandsMixin,pl:mixin:A} at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:597) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:162) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A} at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A} at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A} at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}
[20:38:10] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: NikeeyDE lost connection: Internal server error

**Comment by radiomike** [comment]
That's caused by a recent update to the just enough resources mod on the server. Remove the mod from the mod folder on the server to fix it.

**Comment by SGZ-Creations** [comment]
Is that required for clients too for those joining the server ?

**Comment by radiomike** [comment]
No, just on the server.

**Comment by SGZ-Creations** [comment]
ty

**Comment by NikeeyGH** [comment]
thank you very much, it helped and its going well again
