### ISSUE TITLE
[1.7.10] Used the Teleporter from Allthemodium, can't reconnect to server

### ISSUE THREAD

**Issue by TozTW** [AllTheMods/ATM-6#2222]
ATM6 1.7.10

On my ATM6 server (hosted online), I decided to build a teleporter just to see what it did. I shift right clicked it with an empty hand (as stated by the item description) and it teleported me (in the same way as going through the nether portal does).

However, I never came out on the other side (if there is another side). Instead, I got stuck on the loading chunks or similar menu of Minecraft. I decided to close my game and relaunched it and I have since been unable to join the server. 

Everytime I try to join, it states "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host".

I've tried deleting my player data from the server in the hopes it would reset me, but nothing and I'm running out of options apart from hard resetting the entire server. Please help lol.

Below is a screenshot of what the client and the server states in the console:

![image](https://user-images.githubusercontent.com/89275620/130353913-4f838fad-79da-438c-8367-1253cc31e85d.png)
![image](https://user-images.githubusercontent.com/89275620/130354026-823cbe9b-714a-469d-a752-619871d028e3.png)

[11:48:30] [Netty Epoll Server IO #1/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:item is using 99.5972% of max allowed size
[11:48:30] [Netty Epoll Server IO #1/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:block is using 74.0911% of max allowed size
[11:48:30] [User Authenticator #6/INFO] [minecraft/ServerLoginNetHandler]: UUID of player TozTW is 8aafdae1-5d79-40a5-89d4-231eea1d4e91
[11:48:52] [Server thread/ERROR] [co.lo.cy.ModCyclic/]: ? overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
[11:48:52] [Server thread/ERROR] [co.lo.cy.ModCyclic/]: C PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}
[11:48:52] [Server thread/INFO] [minecraft/PlayerList]: TozTW[/IP REMOVED] logged in with entity id 3109 at (-147.5, 64.0, 69.5)
[11:48:52] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[11:48:52] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /IP REMOVED
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	at jeresources.profiling.ProfileCommand.lambda$register$0(ProfileCommand.java:26) ~[jeresources:0.12.1.127] {re:classloading}
	at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.lambda$test$0(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading}
	at dev.ftb.mods.ftbranks.api.OptionalBoolean.orElseGet(OptionalBoolean.java:58) ~[ftbranks:?] {re:classloading}
	at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:41) ~[ftbranks:?] {re:classloading}
	at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.test(RankCommandPredicate.java:15) ~[ftbranks:?] {re:classloading}
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?] {re:classloading}
	at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:597) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:162) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:dpanvil.mixins.json:MixinPlayerList,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:connectivity.mixins.json:ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
[11:48:55] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: TozTW lost connection: Internal server error
[11:48:55] [Server thread/INFO] [minecraft/DedicatedServer]: TozTW left the game

**Comment by radiomike** [comment]
Looks like you've ended up with just enough resources on your server. Remove that and it will allow you to log back in.
This isn't in the 1.7.10 server pack, so it may be that you've upgraded? If so, you should double check that you've done it properly and there aren't any other left overs from previous versions on your server.
See <https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ>

**Comment by TozTW** [comment]
> Looks like you've ended up with just enough resources on your server. Remove that and it will allow you to log back in.
> This isn't in the 1.7.10 server pack, so it may be that you've upgraded? If so, you should double check that you've done it properly and there aren't any other left overs from previous versions on your server.
> See https://github.com/AllTheMods/ATM-6/wiki/Pack-Upgrade-FAQ

You are correct in the fact that I did upgrade - I use Akaliz server hosting (as recommended by ATM) and they have a simple updating process where it's just a couple of clicks:
![image](https://user-images.githubusercontent.com/89275620/130357236-c5fa5f9e-d837-44cd-abf0-134b3909a922.png)
I've used this to upgrade from 1.7.6 to .7 .8 etc.

I've found the mod and sure enough, after removing it, I finally managed to login - you're a lifesaver.

Do you know whether having the mod may have ducked something up in the world generation etc.?

**Comment by radiomike** [comment]
Ok, not sure whether that actually works as an upgrade, as opposed to just installing over the top of the previous pack. Need to double check that.

As far as world gen etc, no It won't have done anything like that.
