### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by ortum** [AllTheMods/ATM-6#2346]
_Pack version 1.8.2_

I'm trying to set a server up on my PC but the the .bat fails to start the minecraft server. this  is the full error (sorry for the mess): 

[11:42:26] [main/INFO] [minecolonies/]: Tags Loaded
[11:42:26] [main/INFO] [TerraForged/]: Tags Reloaded
[11:42:26] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loading reactor moderators
[11:42:26] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 52 moderator data entries
[11:42:26] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 77 moderator entries
[11:42:26] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loading turbine coils
[11:42:26] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 15 coil data entries
[11:42:27] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 30 coil entries
[11:42:27] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loading fluid transitions
[11:42:27] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 6 transitions data entries
[11:42:27] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 6 liquid transition entries
[11:42:27] [main/INFO] [ne.ro.bi.BiggerReactors/]: Loaded 7 gas transition entries
[11:42:27] [main/INFO] [TerraForged/]: Tags Reloaded
[11:42:29] [main/INFO] [TerraForged/]: Loading vanilla base decorator
[11:42:30] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]
        at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[?:?] {re:classloading}
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?] {re:classloading}
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:153) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?] {}

**Comment by TheRoyalKuzz** [comment]
Same

**Comment by Cinicus** [comment]
Download the newest version of MythicBotany from curse forge. Install the new version to your server and remove the old version. Should fix the issue until they release the update for the pack.

**Comment by ortum** [comment]
> 
> 
> Download the newest version of MythicBotany from curse forge. Install the new version to your server and remove the old version. Should fix the issue until they release the update for the pack.

New error:

[17:08:24] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_301] {}
        at sun.nio.ch.FileDispatcherImpl.write(Unknown Source) ~[?:1.8.0_301] {}
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:1.8.0_301] {}
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_301] {}
        at sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraft.server.SessionLockManager.func_232998_a_(SourceFile:40) ~[?:?] {re:classloading}
        at net.minecraft.world.storage.SaveFormat$LevelSave.<init>(SaveFormat.java:277) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.storage.SaveFormat.func_237274_c_(SaveFormat.java:265) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.Main.main(Main.java:116) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?] {}

**Comment by TheRoyalKuzz** [comment]
New server working after updating the mod

**Comment by Cinicus** [comment]
> > Download the newest version of MythicBotany from curse forge. Install the new version to your server and remove the old version. Should fix the issue until they release the update for the pack.
> 
> New error:
> 
> [17:08:24] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
> java.io.IOException: The process cannot access the file because another process has locked a portion of the file
> at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_301] {}
> at sun.nio.ch.FileDispatcherImpl.write(Unknown Source) ~[?:1.8.0_301] {}
> at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:1.8.0_301] {}
> at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_301] {}
> at sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:1.8.0_301] {}
> at net.minecraft.server.SessionLockManager.func_232998_a_(SourceFile:40) ~[?:?] {re:classloading}
> at net.minecraft.world.storage.SaveFormat$LevelSave.(SaveFormat.java:277) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
> at net.minecraft.world.storage.SaveFormat.func_237274_c_(SaveFormat.java:265) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> at net.minecraft.server.Main.main(Main.java:116) ~[?:?] {re:classloading}
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
> at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
> at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}
> at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
> at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
> at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?] {}
> at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?] {}
> at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?] {}

Try restarting your computer, or making sure that you are not running the server twice. If that doesn't fix it, try re-installing the server, updating MythicBotany, then running the server again.

**Comment by ladylexxie** [comment]
Update Mythic Botany and it will fix the issue, will soon come in 1.8.3
