### ISSUE TITLE
Crashing on startup. Freshly installed.

### ISSUE THREAD

**Issue by TheRocketier** [AllTheMods/ATM-6#2352]
Whenever i launch ATM6 i load a few mods before it just crashes.
   I'm not too sure where i'd go to get logs of what occurred but regardless, i have 8096mb of RAM allocated and i can definitely support it with my system, just not sure what's crashing it.

**Comment by Rice-SD** [comment]
I have the issue on a linux server

[09:11:40] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]

[Debug Log](https://drive.google.com/file/d/1QUlaT6_QUn8sYIH-YoCS9n-zGSqJE0uX/view?usp=sharing)

**Comment by Nevexo** [comment]
Having the same issue, fresh installation 

Java env;
`openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)`

Running on Rocky Linux 8

Error:
`
[15:14:01] [main/INFO] [TerraForged/]: Loading vanilla base decorator     
[15:14:02] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server      
java.lang.RuntimeException: No key seed in MapLike[{"type":"mythicbotany:alfheim_generator","biome_source":{"type":"mythicbotany:alfheim_biomes"}}]; No key seed in MapLike[{"type":"mythicbotany:alfheim_biomes"}]                                                       
        at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[?:?] {re:classloading}                  
        at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?] {re:classloading}
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:153) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302] {}                                                                   
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302] {}                              
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302] {}                                             
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302] {}                                                                                
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2] {}                                                                                                              
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}                                                                                                                                  
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}                                 
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}                             
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}                 
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.4.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.4.jar:?] {}`

**Comment by ladylexxie** [comment]
Manually update Mythic Botany to 1.4.10.
1.8.3 will come out soon to fix the issue.
