### ISSUE TITLE
Client crash with Energy Module & Monitor? 

### ISSUE THREAD

**Issue by iAbuser** [AllTheMods/ATM-6#243]
**Describe the bug**
I created an Energy Module from RFTools and placed it into a monitor and began to tinker with the module settings and crashed. My client displayed saving world and crashed. The crash occurred for anyone on my server that was near the Monitor and Energy Module. If you were away from it, you were fine and didn’t crash. If you attempt to log back into the server you instantly crash since you’re near the Energy Module and Monitor. 

**To Reproduce**
1. : Craft Energy Module and Monitor from RFTools
2. :Connect them together and open the Monitor to configure the module settings
3. :While messing with the module settings you’ll crash
4. : Log back in and crash

**Expected behavior**
We should be able to edit the Energy Module settings in the Monitor with crashing
**Additional context**
To solve the issue and allow everyone to continue loading the chunk that the Energy Module and Monitor were in without crashing, I had to use MCEdit or “Amulet” to load the world and remove the block that was causing the crash. The block removed was the Monitor with the Energy Module loaded into it. 

I will quote the crash report. 

> Description: Rendering Block Entity
java.lang.NullPointerException: Rendering Block Entity
	at mcjty.rftoolsbase.tools.ScreenTextHelper.setup(ScreenTextHelper.java:73) ~[?:1.16-2.0.6] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.modulesclient.EnergyBarClientScreenModule.render(EnergyBarClientScreenModule.java:45) ~[?:1.16-3.0.11] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.modulesclient.EnergyBarClientScreenModule.render(EnergyBarClientScreenModule.java:19) ~[?:1.16-3.0.11] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.client.ScreenRenderer.renderModules(ScreenRenderer.java:246) ~[?:1.16-3.0.11] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.client.ScreenRenderer.renderInternal(ScreenRenderer.java:116) ~[?:1.16-3.0.11] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.client.ScreenRenderer.render(ScreenRenderer.java:50) ~[?:1.16-3.0.11] {re:classloading}
	at mcjty.rftoolsutility.modules.screen.client.ScreenRenderer.func_225616_a_(ScreenRenderer.java:41) ~[?:1.16-3.0.11] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$22630/1418070841.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE render hook after tile rendering,pl:mixin:APP:appliedenergistics2.mixins.json:spatial.SkyRenderMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorWorldRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:MixinWorldRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$476/1896539815.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

**Comment by sifmaster** [comment]
Same problem for our server. It happens two times, if the font of the monitor where changed.

**Comment by jeremiahwinsley** [comment]
Cannot reproduce in 1.3.9, assuming this is fixed. Please reopen if this is still crashing in 1.3.9.
