### ISSUE TITLE
Failed to start 1.16.3 - Ice and Fire & Potions Master errors

### ISSUE THREAD

**Issue by sdieunidou** [AllTheMods/ATM-6#253]
**Describe the bug**
With the version `1.1.9b`, Forge doesn't want to start, due to `Ice and Fire` & `Potions Master` errors.

* [Ice And Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
* [Potions Master](https://www.curseforge.com/minecraft/mc-mods/potionsmaster)

**Errors**
Full log: https://log.mtxserv.com/EUUHX4S

Related errors:

```
[02Nov2020 06:25:01.603] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: iceandfire, class com.github.alexthe666.iceandfire.IceAndFire
--
85 | java.lang.ExceptionInInitializerError: null
86 | at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3]
87 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_231]
88 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_231]
89 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_231]
90 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_231]
91 | at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_231]
92 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1]
93 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?]
94 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_231]
95 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_231]
96 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_231]
97 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_231]
98 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_231]
99 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_231]
100 | Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
101 | at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?]
102 | at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[forge:?]
103 | at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[forge:?]
104 | at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
105 | at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
106 | at com.github.alexthe666.iceandfire.world.IafWorldRegistry.func_236394_a_(IafWorldRegistry.java:150) ~[iceandfire:2.1.0-1.16.3]
107 | at com.github.alexthe666.iceandfire.world.IafWorldRegistry.<clinit>(IafWorldRegistry.java:50) ~[iceandfire:2.1.0-1.16.3]
108 | ... 14 more


109 | [02Nov2020 06:25:02.340] [modloading-worker-0/ERROR [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: potionsmaster, class com.thevortex.potionsmaster.PotionsMaster
110 | java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
111 | at net.minecraftforge.registries.NamespacedDefaultedWrapper.register(NamespacedDefaultedWrapper.java:58) ~[forge:?]
112 | at net.minecraftforge.registries.NamespacedDefaultedWrapper.register(NamespacedDefaultedWrapper.java:74) ~[forge:?]
113 | at net.minecraftforge.registries.NamespacedDefaultedWrapper.func_218381_a(NamespacedDefaultedWrapper.java:42) ~[forge:?]
114 | at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
115 | at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
116 | at net.minecraft.potion.Potions.func_222125_a(SourceFile:69) ~[?:?]
117 | at com.thevortex.potionsmaster.PotionsMaster.<init>(PotionsMaster.java:79) ~[potionsmaster:0.1.23]
118 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_231]
119 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_231]
120 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_231]
121 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_231]
122 | at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_231]
123 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1]
124 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?]
125 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_231]
126 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_231]
127 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_231]
128 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_231]
129 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_231]
130 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_231]


[02Nov2020 06:25:31.020] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 2 errors found
--
232 | [02Nov2020 06:25:31.039] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 990636d4-d026-4b85-baef-f6aa8a4f88d8
233 | [02Nov2020 06:25:31.042] [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
234 | [02Nov2020 06:25:31.049] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2020-11-02_06.25.31-fml.txt


[02Nov2020 06:25:31.054] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
--
236 | net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
237 | Ice and Fire (iceandfire) has failed to load correctly
238 | §7java.lang.ExceptionInInitializerError: null,
239 | Potions Master (potionsmaster) has failed to load correctly
240 | §7java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
241 | ]
242 | at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:262) ~[forge:?]
243 | at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[forge:?]
244 | at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:187) ~[forge:?]
245 | at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]
246 | at net.minecraft.server.Main.main(Main.java:96) ~[?:?]
247 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
248 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
249 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
250 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
251 | at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[minecraft_server.jar:34.1]
252 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?]
253 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?]
254 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?]
255 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?]
256 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?]
257 | at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [minecraft_server.jar:?]
258 | at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [minecraft_server.jar:?]
259 | at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [minecraft_server.jar:?]
```

**Crash Report**

Full log: https://log.mtxserv.com/eYp2lPp

**To Reproduce**
* Minecraft 1.16.3
* ATM - 1.1.9b - Server
* Forge mod loading, version 34.1.33, for MC 1.16.3 with MCP 20200911.084530

**Expected behavior**
Server must start.

**Comment by sdieunidou** [comment]
**Crash Report**

Full log: https://log.mtxserv.com/eYp2lPp

**Comment by ovingiv** [comment]
Same issue applies to ATM6 - 1.2.0 however, I manually updated Ice and Fire to 2.1.1 1.16.3 and that no longer was an issue. However, potionsmaster still is causing issues. I'm going to attempt to use a older version of forge and try.

**Comment by sdieunidou** [comment]
Same issue with the new `1.2.0` (latest version of Forge for mc 1.16.3).

With forge `34.1.25`, everything works, ty @ovingiv
