### ISSUE TITLE
[Bug]: Nether not loading Terrain, ServerWorldLightManager

### ISSUE THREAD

**Issue by DeFYzz** [AllTheMods/ATM-6#2563]
### Possible Fixes

Yes

### Modpack Version

1.8.5

### What happened?

I entered the Nether and noticed that some Chunks weren't loading. After Teleporting out and entering again I'm stuck at "Loading Terrain..."

The Log says that a Thread died.

Excerpt:
`[11Oct2021 14:20:33.664] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: DeFYzz has made the advancement [We Need to Go Deeper]
[11Okt2021 14:20:33.665] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] DeFYzz has made the advancement [We Need to Go Deeper]
[11Okt2021 14:20:33.738] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1689 advancements
[11Oct2021 14:20:33.804] [Server thread/WARN] [net.minecraft.network.play.ServerPlayNetHandler/]: DeFYzz moved wrongly!
[11Okt2021 14:20:33.974] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1689 advancements
[11Okt2021 14:20:35.821] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Received passengers for unknown entity
[11Okt2021 14:20:37.678] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Received passengers for unknown entity
[11Okt2021 14:20:38.713] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Received passengers for unknown entity
[11Oct2021 14:20:41.189] [Worker-Main-120/WARN] [net.minecraft.util.Util/]: Worker-Main-120 died
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_242]
	at net.minecraft.world.server.ServerWorldLightManager.func_223117_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215603_b(SourceFile:170) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223119_a(SourceFile:108) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_242]
[11Oct2021 14:20:41.191] [Worker-Main-120/ERROR] [net.minecraft.util.Util/]: Caught exception in thread Thread[Worker-Main-120,5,main]
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_242]
	at net.minecraft.world.server.ServerWorldLightManager.func_223117_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215603_b(SourceFile:170) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223119_a(SourceFile:108) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]
[11Okt2021 14:21:03.394] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1689 advancements
[11Okt2021 14:21:14.497] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1694 advancements
[11Okt2021 14:21:25.445] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1699 advancements
[11Okt2021 14:21:25.943] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1700 advancements
[11Okt2021 14:21:36.972] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1726 advancements
[11Okt2021 14:21:43.514] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1740 advancements
[11Okt2021 14:26:30.726] [Render thread/INFO] [minecolonies/]: Removed all colony views
[11Okt2021 14:27:20.563] [Render thread/INFO] [minecolonies/]: Removed all colony views`

### latest.log

https://gist.github.com/DeFYzz/190eab7461ce352a483fef90d3bfa710

**Comment by jeremiahwinsley** [comment]
Possibly fixed in 1.8.9 with Embur Bog being disabled. It will require a nether reset to clear out any existing ones. Please let us know if you are still having this issue after updating + resetting.
