### ISSUE TITLE
[Crash] Integrated Dynamics?

### ISSUE THREAD

**Issue by LunixNovalis** [AllTheMods/ATM-6#2773]
Mod Pack Version: 1.8.10

I'm getting a client crash, to login, from my server when crafting/placing Integrated Dynamics Blocks. I can load back into the server and the block is placed and working so nothing is missing. There wasn't any crash report, the client only crashed to the server login screen, and the server kept running. The only thing I could find was in the Latest.log file. Below is what I found.

[07Dec2021 19:13:38.579] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /[IP Address]
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArithmeticException: / by zero
	at org.cyclops.integrateddynamics.capability.energystorage.EnergyStorageItemBlockEnergyContainer.receiveEnergy(EnergyStorageItemBlockEnergyContainer.java:82) ~[integrateddynamics:1.10.5]
	at cofh.thermal.innovation.item.RFCapacitorItem.lambda$inventoryTick$2(RFCapacitorItem.java:95) ~[thermal_innovation:1.3.0]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[forge:?]
	at cofh.thermal.innovation.item.RFCapacitorItem.func_77663_a(RFCapacitorItem.java:95) ~[thermal_innovation:1.3.0]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434) ~[?:?]
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:238) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:487) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more

**Comment by jeremiahwinsley** [comment]
Looks like an interaction between an Integrated Dynamics battery and a Thermal capacitor. Tested on 1.8.14 and I'm not able to replicate the issue, so this may have been fixed by an Integrated Dynamics update already. Let me know if the update does not fix the issue for you.
