### ISSUE TITLE
[Bug]: 1.8.19 Server Pack fails to launch using batch file

### ISSUE THREAD

**Issue by hehehe426** [AllTheMods/ATM-6#2951]
### Possible Fixes

Yes

### Modpack Version

other

### What happened?

When running the serverstart batch file for a freshly downloaded 1.8.19 server pack, it immediately crashes with the following error:

Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x5e4c8041) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x5e4c8041
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

### latest.log

https://gist.github.com/hehehe426/4376792cc54f00a94bb67b4fdb7cfcb7

**Comment by jeremiahwinsley** [comment]
Java 16 isn't supported, ATM6 is compatible with Java 8-15. See https://github.com/AllTheMods/ATM-6/wiki/Java-Versions
