### ISSUE TITLE
[Crash]: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05) 1.8.20/1.8.19 FIXED

### ISSUE THREAD

**Issue by NworkYakzI** [AllTheMods/ATM-6#2988]
### Possible Fixes

THE PROBLEM WAS ENTYTIES OVER 150 000 WITH MYSTICAL 

/kill @e[type=item]
say hello
[17:17:58] [Server thread/INFO] [minecraft/DedicatedServer]: Killed 152440 entities

### Modpack Version

1.8.20

### What happened?

Hello there !

I'm running very well atm6 and we love it. But since 2 days, the server start to crash after a backup while we are playing. After that, I reload a backup from the server that I manage. This hae work. After 3 hours of play and farm, the server start again to crash just after a backup. When this happen, I were on 1.8.19 and now i'm running 1.8.20 with the same map. I create a new server with a new gen. that was fine. And I try it after with our word. Now the server is able to launch but when a single player join, the server crash.

the startup line : java -Xms128M -Xmx24576M -Dterminal.jline=false -Dterminal.ansi=true -jar forge-1.16.5-36.2.28.jar

I'm running the server on Pterodactyl panel, on ubuntu, up to date.
Dual Xeon E2560 with 96 gb of ram and Raid image on SSD samsung sata.

we will appreciate any help
thank you

ps: sorry for my english, I'm french

### Crash Log

https://gist.github.com/NworkYakzI/877c4f1f8a2bb55fb3b2b152ca264724

**Comment by NworkYakzI** [comment]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_312] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_312] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312] {}
Caused by: java.lang.NullPointerException: Registry Object not present: resourcefulbees:catnip_honeycomb
        at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_312] {}
        at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:mixin,re:classloading}
        at com.resourcefulbees.resourcefulbees.data.RecipeBuilder.centrifugeRecipe(RecipeBuilder.java:270) ~[resourcefulbees:1.16.5-0.10.4] {re:classloading}
        at com.resourcefulbees.resourcefulbees.data.RecipeBuilder.lambda$onResourceManagerReload$6(RecipeBuilder.java:54) ~[resourcefulbees:1.16.5-0.10.4] {re:classloading}
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_312] {}
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1507) ~[?:1.8.0_312] {}
        at com.resourcefulbees.resourcefulbees.data.RecipeBuilder.func_195410_a(RecipeBuilder.java:44) ~[resourcefulbees:1.16.5-0.10.4] {re:classloading}
        at net.minecraft.resources.IResourceManagerReloadListener.func_232635a(IResourceManagerReloadListener.java:18) ~[?:?] {re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_312] {}
        ... 77 more

**Comment by NworkYakzI** [comment]
I able to go in the save in solo, but very very lagy, 1 fps, and everything is waiting for server

**Comment by NworkYakzI** [comment]
update in solo world : when I come around my base the game crash ! I'm using refined storage, bigger reactor, botania, mystical, bee, an spawner with nether stars (2) one with wither skeleton, and the other with blue slime

**Comment by ninko76** [comment]
Mine has the same error whenever I try to use a Mekanism Laser.
