### ISSUE TITLE
serve cant run correctly

### ISSUE THREAD

**Issue by ShirakamiFubuk1** [AllTheMods/ATM-6#30]
i have download ATM0.11 ver for last month,yesterday I wanna get update，but the cmd responded with follow codes. Thx

**Comment by ShirakamiFubuk1** [comment]
i have download ATM0.11 ver for last month,yesterday I wanna get update，but the cmd responded with follow codes. Thx
==========================================
2020-07-31 09:36:13,866 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2020-07-31 09:36:13,928 main WARN Advanced terminal features are not available in this environment
2020-07-31 09:36:13,978 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[32m[09:36:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.88, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, nogui]
[m[32m[09:36:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_261 by Oracle Corporation
[m[32m[09:36:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[mException in thread "main" [32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.MixinEnvironment$Phase.<clinit>(MixinEnvironment.java:99)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.service.MixinServiceAbstract.getInitialPhase(MixinServiceAbstract.java:87)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:141)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:84)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap$Values.forEach(Unknown Source)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.net.URLClassLoader.findClass(Unknown Source)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[m[32m[09:36:14] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         ... 14 more
[m[09:36:14] [INFO] Server has been stopped, it has started 1 times in 60min
[09:36:14] [INFO] Restarting server in 10 seconds, press ctrl+c to stop
