### ISSUE TITLE
[Question]: confused on what I did wrong

### ISSUE THREAD

**Issue by Sithic** [AllTheMods/ATM-6#3057]
### What would you like to know?

I got this error and don't really know what I need to do.

`2022-04-26 23:43:41,810 main WARN Advanced terminal features are not available in this environment
[23:43:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.33, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[23:43:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.3 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x7ff95560) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x7ff95560
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Restarting automatically in 10 seconds (press Ctrl + C to cancel)
`

Thanks in advance for any help,

**Comment by thevortex** [comment]
looks like you are using java 17 for minecraft 1.16.5, which will not work, java 17 is for minecraft 1.18+, you want java 8 or java 11(better)

**Comment by Sithic** [comment]
> looks like you are using java 17 for minecraft 1.16.5, which will not work, java 17 is for minecraft 1.18+, you want java 8 or java 11(better)

sorry to reopen, but how would I change what version the server uses? I am using Java 8 on my MultiMC version but idk where the java the server uses is located (i assume the server folders but i can't find them even with file explorer search)
