### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Trsif** [AllTheMods/ATM-6#3129]
java.lang.NoClassDefFoundError: appeng/tile/networking/WirelessTileEntity$Anonymous$406488192bc94558a1247d89886f04f0
	at appeng.tile.networking.WirelessTileEntity.handler$zlo000$init(WirelessTileEntity.java:531) ~[appliedenergistics2:8.4.7] {re:mixin,re:classloading,pl:mixin:APP:AEInfinityBooster.mixins.json:MixinWirelessTileEntity,pl:mixin:A}
	at appeng.tile.networking.WirelessTileEntity.<init>(WirelessTileEntity.java:62) ~[appliedenergistics2:8.4.7] {re:mixin,re:classloading,pl:mixin:APP:AEInfinityBooster.mixins.json:MixinWirelessTileEntity,pl:mixin:A}
	at appeng.bootstrap.TileEntityBuilder.lambda$null$2(TileEntityBuilder.java:110) ~[appliedenergistics2:8.4.7] {re:classloading,pl:runtimedistcleaner:A}
	at appeng.block.AEBaseTileBlock.createTileEntity(AEBaseTileBlock.java:113) ~[appliedenergistics2:8.4.7] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:106) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:363) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:390) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_175625_s(World.java:598) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at appeng.me.GridNode.findGridHost(GridNode.java:430) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.me.GridNode.findConnections(GridNode.java:349) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.me.GridNode.updateState(GridNode.java:194) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:138) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:131) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:263) ~[appliedenergistics2:8.4.7] {re:classloading,pl:runtimedistcleaner:A}
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:529) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.tile.networking.CableBusTileEntity.onReady(CableBusTileEntity.java:189) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.hooks.ticking.TickHandler.readyTiles(TickHandler.java:397) ~[appliedenergistics2:8.4.7] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onWorldTick(TickHandler.java:293) ~[appliedenergistics2:8.4.7] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:86) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.ClassNotFoundException: appeng.tile.networking.WirelessTileEntity$Anonymous$406488192bc94558a1247d89886f04f0
	at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	... 29 more
	Suppressed: java.lang.SecurityException: class "appeng.tile.networking.WirelessTileEntity$Anonymous$406488192bc94558a1247d89886f04f0"'s signer information does not match signer information of other classes in the same package
		at java.lang.ClassLoader.checkCerts(ClassLoader.java:1151) ~[?:?] {}
		at java.lang.ClassLoader.preDefineClass(ClassLoader.java:906) ~[?:?] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1015) ~[?:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
		at appeng.tile.networking.WirelessTileEntity.handler$zlo000$init(WirelessTileEntity.java:531) ~[appliedenergistics2:8.4.7] {re:mixin,re:classloading,pl:mixin:APP:AEInfinityBooster.mixins.json:MixinWirelessTileEntity,pl:mixin:A}
		at appeng.tile.networking.WirelessTileEntity.<init>(WirelessTileEntity.java:62) ~[appliedenergistics2:8.4.7] {re:mixin,re:classloading,pl:mixin:APP:AEInfinityBooster.mixins.json:MixinWirelessTileEntity,pl:mixin:A}
		at appeng.bootstrap.TileEntityBuilder.lambda$null$2(TileEntityBuilder.java:110) ~[appliedenergistics2:8.4.7] {re:classloading,pl:runtimedistcleaner:A}
		at appeng.block.AEBaseTileBlock.createTileEntity(AEBaseTileBlock.java:113) ~[appliedenergistics2:8.4.7] {re:classloading}
		at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:106) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:363) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:390) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.world.World.func_175625_s(World.java:598) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
		at appeng.me.GridNode.findGridHost(GridNode.java:430) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.me.GridNode.findConnections(GridNode.java:349) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.me.GridNode.updateState(GridNode.java:194) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:138) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:131) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:263) ~[appliedenergistics2:8.4.7] {re:classloading,pl:runtimedistcleaner:A}
		at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:529) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.tile.networking.CableBusTileEntity.onReady(CableBusTileEntity.java:189) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.hooks.ticking.TickHandler.readyTiles(TickHandler.java:397) ~[appliedenergistics2:8.4.7] {re:classloading}
		at appeng.hooks.ticking.TickHandler.onWorldTick(TickHandler.java:293) ~[appliedenergistics2:8.4.7] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:86) ~[forge:?] {re:classloading}
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
		at java.lang.Thread.run(Thread.java:834) [?:?] {}

**Comment by jeremiahwinsley** [comment]
Looks like you might have a corrupted AE2 jar, try replacing it with a fresh download from here: https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3608871

**Comment by Trsif** [comment]
bug with [AEInfinityBooster-1.16.5-1.0.04.jar] removing it fixed the issue
