### ISSUE TITLE
Elemental Craft Crashes Server When Joining World.

### ISSUE THREAD

**Issue by Sammi-Husky** [AllTheMods/ATM-6#343]
**Describe the bug**
Server crashed immediately upon placing an inert Crystal on Elemental Craft infuser, crashes on all subsequent logins to the world. 

**Additional context**
Running ATM6 - 1.3.0

Relevant lines from log file regarding the crash:
```
[19Nov2020 14:16:26.620] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class sirttas/elementalcraft/particle/ParticleHelper for invalid dist DEDICATED_SERVER
[19Nov2020 14:16:26.630] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 82c7eef9-4ffd-4af7-ba8d-a44e2f934a41
[19Nov2020 14:16:26.636] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: java.lang.RuntimeException: Attempted to load class sirttas/elementalcraft/particle/ParticleHelper for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:35.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
	at sirttas.elementalcraft.block.instrument.TileInstrument.onProgress(TileInstrument.java:70) ~[elementalcraft:1.16.3-2.4.6]
	at sirttas.elementalcraft.block.instrument.TileInstrument.makeProgress(TileInstrument.java:62) ~[elementalcraft:1.16.3-2.4.6]
	at sirttas.elementalcraft.block.instrument.TileInstrument.func_73660_a(TileInstrument.java:50) ~[elementalcraft:1.16.3-2.4.6]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more
```

**Comment by Sirttas** [comment]
Duplicate of https://github.com/AllTheMods/ATM-6/issues/308.
Update to 1.3.1

**Comment by Sammi-Husky** [comment]
Dang. I thought i searched the issue tracker well enough before posting, my apologies. Closing his now.
