### ISSUE TITLE
6.0.9.a crashes on electric furnace

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-6#4]
---- Minecraft Crash Report ----
// My bad.

Time: 11/07/2020, 10:51
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at com.maciej916.indreb.common.block.impl.machines.electric_furnace.TileEntityElectricFurnace.onUpdate(Tile
EntityElectricFurnace.java:109) ~[?:1.16.1-0.7.1] {re:classloading}
        at com.maciej916.indreb.common.tile.IndRebTileEntity.func_73660_a(IndRebTileEntity.java:174) ~[?:1.16.1-0.7
.1] {re:classloading}
        at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?] {re:classloading,pl:accesstransformer:B,r
e:mixin,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:a
ccesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?] {re:classloading,pl:a
ccesstransformer:B}
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?] {re:class
loading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl
:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classl
oading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
-- Block entity being ticked --
Details:
        Name: indreb:electric_furnace // com.maciej916.indreb.common.block.impl.machines.electric_furnace.TileEntityElectricFurnace
        Block: Block{indreb:electric_furnace}[active=false,facing=north]
        Block location: World: (741,63,-1920), Chunk: (at 5,3,0 in 46,-120; contains blocks 736,0,-1920 to 751,255,-1905), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
        Block: Block{indreb:electric_furnace}[active=false,facing=north]
        Block location: World: (741,63,-1920), Chunk: (at 5,3,0 in 46,-120; contains blocks 736,0,-1920 to 751,255,-1905), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
Stacktrace:
        at net.minecraft.world.World.func_217391_K(World.java:533)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364)

**Comment by whatthedrunk** [comment]
Mod has been removed from version 0.10 thanks for the report! We will be adding the mod back in the future but for now we have Mekanism added.
