### ISSUE TITLE
Auto Attack Pedestral on Blaze Spawner crashes the game.

### ISSUE THREAD

**Issue by Lulloser** [AllTheMods/ATM-6#434]
I put a Pedestral on a Spawner with an Autoattacker and it hit me then crashed the game and I cannot load the map again without it crashing.

On 1.3.3

**Comment by Lulloser** [comment]
After crashing 3 times, it did let me join my World.

**Comment by Lulloser** [comment]
It crashes again with this log:
[04:33:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$26598/990284017.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
	at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_51]
	at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeAttacker.upgradeAction(ItemUpgradeAttacker.java:174) ~[?:0.8h]
	at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeAttacker.updateAction(ItemUpgradeAttacker.java:141) ~[?:0.8h]
	at com.mowmaster.pedestals.tiles.PedestalTileEntity.func_73660_a(PedestalTileEntity.java:1235) ~[?:0.8h]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 6 more

**Comment by jeremiahwinsley** [comment]
Fixed in 1.3.9.
