### ISSUE TITLE
Crash when loading Pedestal in the world

### ISSUE THREAD

**Issue by Demz1001** [AllTheMods/ATM-6#453]
So When I updated to 1.3.3 and trying to load my world the game crashes how do I fix this.

The log it made.
[latest.log](https://github.com/AllTheMods/ATM-6/files/5616681/latest.log)

**Comment by ViRb3** [comment]
```
Caused by: java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[?:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[?:?]
	at com.mowmaster.pedestals.tiles.PedestalTileEntity.func_70301_a(PedestalTileEntity.java:80) ~[?:0.8h]
```

Issue is in this mod: https://www.curseforge.com/minecraft/mc-mods/pedestals

**Comment by Demz1001** [comment]
Found a little fix by removing the pedestal mod and loading the world all from pedestal gets removed and it doesn't crash anymore.
