### ISSUE TITLE
Crash when trying to load

### ISSUE THREAD

**Issue by giddorah** [AllTheMods/ATM-6#54]
Hi,

I haven't changed anything. Just started the pack, created a world, played for a few hours, saved and was supposed to load back into the world to let it run.

This appears immediately.
![image](https://user-images.githubusercontent.com/20879348/89796948-97328000-db2a-11ea-93d2-744826254ac8.png)

Clicking "Safe Mode" does nothing.

I downloaded the pack today, so **I'm on 0.24b**.

**This is in my log-files:**

[16:58:54] [Render thread/WARN]: Couldn't get pack info for: java.nio.channels.ClosedChannelException
[16:58:54] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.lang.NullPointerException: null
	at net.minecraftforge.fml.packs.ResourcePackLoader.lambda$getPackNames$4(ResourcePackLoader.java:66) ~[?:?]
	at net.minecraftforge.fml.packs.ResourcePackLoader$$Lambda$11958/803591569.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraftforge.fml.packs.ResourcePackLoader.getPackNames(ResourcePackLoader.java:66) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.getModPacks(ForgeHooks.java:1242) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240772_a_(MinecraftServer.java:1307) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1805) ~[?:?]
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1660) [?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1633) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:408) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:319) [?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:261) [?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$16821/2127439607.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$16820/664618517.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$12560/647901154.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.106.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/897098843.call(Unknown Source) [forge-1.16.1-32.0.106.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]

**Comment by WhitePhant0m** [comment]
It's fixed in 0.25 but curse hasn't yet approved the update
