### ISSUE TITLE
My game continuously crash before open the world

### ISSUE THREAD

**Issue by MattWinchester89** [AllTheMods/ATM-6#584]
Hi! I'm playing ATM6 from one/two months and today (after updating the MP) I can't open my world! It's continuously crashing. The problem is, I'm recording videos for my channel... so i want to record other videos in this wonderful modpack! :P 
[2020-12-17-3.log](https://github.com/AllTheMods/ATM-6/files/5708916/2020-12-17-3.log) 

I send you the latest log from my last attemp to join my world! I hope to fix it. Another thing, I can't find dragons or any creature from Ice&Fire Mod. I went also in the allthemodium dimension from Nether but still I can't find dragons! :/

**Comment by ViRb3** [comment]
Sounds like a bug in the void miner:
```
Caused by: java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401) ~[guava-21.0.jar:?]
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$1.hasNext(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.util.registry.DynamicRegistries.func_243607_a(DynamicRegistries.java:97) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:82) ~[?:?]
	at com.valkyrieofnight.vlib.core.util.wrapped.VLID.from(VLID.java:79) ~[valkyrielib:?]
	at com.valkyrieofnight.envirotech.m_voidminer.tile.VoidMinerCCUTile.updateDropList(VoidMinerCCUTile.java:216) ~[envirotech:1.16.4-3.0.4.1]
```

Looks like it's tracked here: https://github.com/ValkyrieofNight/EnvironmentalTech/issues/228

**Comment by ViRb3** [comment]
Duep of #575
