### ISSUE TITLE
Immersive Engineering crash(?)

### ISSUE THREAD

**Issue by CrowSR** [AllTheMods/ATM-6#6]
I installed the modpack as-is, no extra mods were added nor were any deactivated.

MultiMC log: https://paste.ee/p/YHuUd

**Comment by Homeboy87** [comment]
have an same error
my friend build the Coke Oven from Immersive Engenieering and the Server crashs, when the chunk will be loaded

> [21:41:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:859) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}
Caused by: java.lang.NullPointerException
        at blusunrize.immersiveengineering.api.crafting.CokeOvenRecipe.findRecipe(CokeOvenRecipe.java:61) ~[?:?] {re:classloading}
        at blusunrize.immersiveengineering.common.blocks.stone.CokeOvenTileEntity.isStackValid(CokeOvenTileEntity.java:293) ~[?:?] {re:classloading}
        at blusunrize.immersiveengineering.common.util.inventory.IEInventoryHandler.insertItem(IEInventoryHandler.java:77) ~[?:?] {re:classloading}
        at net.minecraftforge.items.VanillaInventoryCodeHooks.insertStack(VanillaInventoryCodeHooks.java:170) ~[?:?] {re:classloading}
        at net.minecraftforge.items.VanillaInventoryCodeHooks.putStackInInventoryAllSlots(VanillaInventoryCodeHooks.java:158) ~[?:?] {re:classloading}
        at net.minecraftforge.items.VanillaInventoryCodeHooks.lambda$insertHook$2(VanillaInventoryCodeHooks.java:137) ~[?:?] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.lambda$map$0(LazyOptional.java:184) ~[?:?] {re:mixin,re:classloading}
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:116) ~[?:?] {re:mixin,re:classloading}
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:219) ~[?:?] {re:mixin,re:classloading}
        at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:151) ~[?:?] {re:classloading}
        at net.minecraft.tileentity.HopperTileEntity.func_145883_k(HopperTileEntity.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.tileentity.HopperTileEntity.func_200109_a(HopperTileEntity.java:105) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.tileentity.HopperTileEntity.func_73660_a(HopperTileEntity.java:92) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

after disabeling Immersive on Server and Client, we can login again
``

**Comment by whatthedrunk** [comment]
Looks like he is working on the issue. I will update the pack as soon as the mod updates. Thanks!
