### ISSUE TITLE
Game Crashing When creating new world 1.3.6

### ISSUE THREAD

**Issue by ZenoWraith** [AllTheMods/ATM-6#605]
java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:184) ~[?:7.6.0.62]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:87) ~[?:7.6.0.62]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[?:7.6.0.62]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[?:7.6.0.62]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[?:7.6.0.62]
	at mezz.jei.recipes.RecipeManager.addRecipe(RecipeManager.java:144) [?:7.6.0.62]
	at mezz.jei.recipes.RecipeManager.addRecipeTyped(RecipeManager.java:105) [?:7.6.0.62]
	at mezz.jei.recipes.RecipeManager.addRecipes(RecipeManager.java:98) [?:7.6.0.62]
	at mezz.jei.recipes.RecipeManager.<init>(RecipeManager.java:90) [?:7.6.0.62]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:142) [?:7.6.0.62]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [?:7.6.0.62]
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:128) [?:7.6.0.62]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$1(ClientLifecycleHandler.java:98) [?:7.6.0.62]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$25316/1199763905.accept(Unknown Source) [?:7.6.0.62]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2933/1923962747.invoke(Unknown Source) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:699) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$30068/284140228.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/1632677830.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
[11:53:16] [Render thread/INFO]: Building recipe registry took 1.024 s
[11:53:16] [Render thread/INFO]: Building runtime...
[11:53:16] [Render thread/INFO]: Building runtime took 60.61 ms
[11:53:16] [Render thread/INFO]: Ingredients are being added at runtime: 1 net.minecraft.item.ItemStack
[11:53:16] [Render thread/INFO]: Ingredients are being added at runtime: 24 net.minecraft.item.ItemStack
[11:53:16] [Render thread/INFO]: Ingredients are being removed at runtime: 31 net.minecraft.item.ItemStack
[11:53:16] [Render thread/INFO]: Ingredients are being added at runtime: 1 net.minecraft.item.ItemStack
[11:53:16] [Render thread/INFO]: Ingredients are being removed at runtime: 10 net.minecraft.item.ItemStack
[11:53:16] [Render thread/ERROR]: Could not find any matching ingredients to remove: 1 FluidDummyItem[dummy_fluid_item] appliedenergistics2:dummy_fluid_item
[11:53:16] [Render thread/INFO]: Ingredients are being removed at runtime: 1 net.minecraft.item.ItemStack
[11:53:16] [Render thread/INFO]: Starting JEI took 17.96 s

**Comment by whatthedrunk** [comment]
Let me know if you are having issues on 1.5.0 still.
