### ISSUE TITLE
6-1.3.6b - Crash when going through the portal after defeating the dragon in the end (Mac)

### ISSUE THREAD

**Issue by nbitting** [AllTheMods/ATM-6#624]
**After I beat the dragon in the end, I tried going through the portal, but it crashes every time. 

See crash info below:**
MultiMC version: 0.6.11-1370

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/ATM 6 - 1.3.6b/minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java is version 1.8.0_271, using 64-bit architecture.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/ATM 6 - 1.3.6b/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/ATM 6 - 1.3.6b/minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 35.1.13 --fml.mcVersion 1.16.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20201102.104115

Window size: max (if available)

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: ATM 6 - 1.3.6b", -XstartOnFirstThread, -Xms512m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 4370

Crash Report ----
// Ouch. That hurt :(

Time: 12/20/20 9:02 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/thevortex/potionsmaster/render/util/xray/Render$Profile
	at com.thevortex.potionsmaster.render.util.xray.Render.drawOres(Render.java:56) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
	at com.thevortex.potionsmaster.render.util.xray.Events.onWorldRenderLast(Events.java:55) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_412_Events_onWorldRenderLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:609) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13-launcher.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.ClassNotFoundException: com.thevortex.potionsmaster.render.util.xray.Render$Profile
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_271] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271] {}
	... 30 more
	Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.thevortex.potionsmaster.render.util.xray.Render$Profile
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271] {}
		at com.thevortex.potionsmaster.render.util.xray.Render.drawOres(Render.java:56) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
		at com.thevortex.potionsmaster.render.util.xray.Events.onWorldRenderLast(Events.java:55) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_412_Events_onWorldRenderLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154) ~[forge:?] {re:classloading}
		at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:609) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
		at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13-launcher.jar:35.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
		at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
		at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
		at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
		at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
		at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
	Caused by: java.nio.channels.ClosedChannelException
		at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) ~[?:1.8.0_271] {}
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:276) ~[?:1.8.0_271] {}
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:50) ~[?:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:952) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:931) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1500) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1430) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:547) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_271] {}
		at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_271] {}
		at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_271] {}
		at net.minecraftforge.fml.loading.ModJarURLHandler$ModJarURLConnection.getInputStream(ModJarURLHandler.java:87) ~[forge-1.16.4-35.1.13-launcher.jar:35.1] {}
		at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:174) ~[modlauncher-8.0.6.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-8.0.6.jar:?] {}
		... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.thevortex.potionsmaster.render.util.xray.Render.drawOres(Render.java:56) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
	at com.thevortex.potionsmaster.render.util.xray.Events.onWorldRenderLast(Events.java:55) ~[potionsmaster:0.1.30-1.16.4-35.1.13] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_412_Events_onWorldRenderLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:609) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['nbitting'/205, l='ClientLevel', x=-1206.50, y=72.00, z=3813.50]]
	Chunk stats: Client Chunk Cache: 625, 14
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,63,80), Chunk: (at 0,3,0 in 8,5; contains blocks 128,0,80 to 143,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2310241 game time, 2705017 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:sun_brightness_client,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13-launcher.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.4
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1446969704 bytes (1379 MB) / 7871660032 bytes (7507 MB) up to 7871660032 bytes (7507 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
		kotori_scala@2.13.3-build-6
	
	Crash Report UUID: bcecec5e-9dd3-4475-aa62-485a15bacc80
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon Pro 5500M OpenGL Engine GL version 2.1 ATI-3.8.24, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

[21:02:28] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/ATM 6 - 1.3.6b/minecraft/crash-reports/crash-2020-12-20_21.02.28-client.txt
Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

**Comment by whatthedrunk** [comment]
Can't seem to replicate let me know if it's still happening on 1.5.0
