### ISSUE TITLE
[1.3.7] Cyclic - Advanced Crafting Stick crashes server when clicking "Empty the grid" with a full inventory

### ISSUE THREAD

**Issue by Perryman** [AllTheMods/ATM-6#685]
**Describe the bug**
If there is no room in the player's inventory and there are items stored in the Advanced Crafting Stick from the Cyclic mod, clicking "Empty the grid" crashes the server.

**To Reproduce**
1. Get an Advanced Crafting Stick from Cyclic
2. Put some items into the Advanced Crafting Stick
3. Fill your inventory with items such that there will be no space remaining for the ones in the stick
4. Click "Empty the grid"
5. See error (log attached)

**Expected behavior**
Either the items should be forced into the world, or an error message should appear, or nothing at all should happen.

**Additional context**
```
[27.12 21:04:57] [Server] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
[27.12 21:04:57] [Server] java.lang.AbstractMethodErrorcom.lothrazar.cyclic.item.crafting.CraftingBagContainer.transferStackInSlot(Lnet/minecraft/entity/player/PlayerEntity;I)Lnet/minecraft/item/ItemStack;
[27.12 21:04:57] [Server] 	at com.lothrazar.cyclic.net.PacketCraftAction.performAction(PacketCraftAction.java:75) ~[cyclic:1.16.4-1.0.{re:classloading}
[27.12 21:04:57] [Server] 	at com.lothrazar.cyclic.net.PacketCraftAction.lambda$handle$0(PacketCraftAction.java:63) ~[cyclic:1.16.4-1.0.{re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at com.lothrazar.cyclic.net.PacketCraftAction.handle(PacketCraftAction.java:57) ~[cyclic:1.16.4-1.0.{re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_{}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
[27.12 21:04:57] [Server] 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
[27.12 21:04:57] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_{}
[27.12 21:04:57] [Server] 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
[27.12 21:04:57] [Server] 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[27.12 21:04:57] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[27.12 21:04:57] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[27.12 21:04:57] [Server] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ########-####-####-####-############
[27.12 21:04:59] [Multicraft] Server shut down (running)
```

**Comment by Perryman** [comment]
https://github.com/Lothrazar/Cyclic/blob/08ddde01667fb64d9b31bbff3ce7041705d07090/update.json

**Comment by Perryman** [comment]
Moved to #695, this is a more widespread issue in Cyclic 1.0.0, and in my opinion it should be updated to 1.0.2 to resolve issues.
