### ISSUE TITLE
Upgrade 1.3.5 to 1.3.7 - Can't load previous World

### ISSUE THREAD

**Issue by waybaker** [AllTheMods/ATM-6#698]
**Describe the bug**
I upgraded from 1.3.5 to 1.3.7 and when I attempt to log in, the server crashes.
This does not happen on a clean world, only if I try to use the world from 1.3.5.

**To Reproduce**
1. Play for weeks on 1.3.5 and then upgrade to 1.3.7
2. Attempt to log in
3. Experience crash

**Expected behavior**
World should load and work correctly.

**Additional context**
Crash Log:
`[30Dec2020 14:50:46.374] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_272]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_272]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_272]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_272]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_272]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_272]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_272]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?]
	at net.minecraft.entity.monster.EndermiteEntity.func_70636_d(SourceFile:134) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.monster.EndermiteEntity.func_70071_h_(SourceFile:110) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more`

**Comment by waybaker** [comment]
Here is an actual crash report.  Seems an endermite is causing the issue when I try to log in.
[crash-2020-12-30_16.03.32-server.txt](https://github.com/AllTheMods/ATM-6/files/5755718/crash-2020-12-30_16.03.32-server.txt)

**Comment by waybaker** [comment]
I was able to log in with another account and go to the location noted in the crash report and couldn't find anything there.  Logged out and logged back in with the normal account and it worked.
