### ISSUE TITLE
1.3.9 Repeated Server Crash. 

### ISSUE THREAD

**Issue by kjchiamu** [AllTheMods/ATM-6#749]
**Describe the bug**
Server crashes during startup. 

**To Reproduce**
1. Start Server.
2.  Wait for it to crash.

**Expected behavior**
Server Starts.

**Screenshots**

**Additional context**
Crash Report:
[https://pastebin.com/MSTR7a5s](url)

Below is the console output for the error.

[05Jan2021 11:42:26.608] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/entity/RatUtils
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:1582) ~[rats:7.0.3-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.entity.RatUtils
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_272]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:1582) ~[rats:7.0.3-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more
	Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.github.alexthe666.rats.server.entity.RatUtils
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
		at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:1582) ~[rats:7.0.3-1.16.3]
		at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
		at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
		at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
		at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
		at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
		at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
	Caused by: java.nio.channels.ClosedChannelException
		at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) ~[?:1.8.0_272]
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:276) ~[?:1.8.0_272]
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:50) ~[?:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:973) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:966) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:952) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1528) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1458) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:562) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_272]
		at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_272]
		at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_272]
		at net.minecraftforge.fml.loading.ModJarURLHandler$ModJarURLConnection.getInputStream(ModJarURLHandler.java:87) ~[atm6.jar:35.1]
		at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:174) ~[modlauncher-8.0.6.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-8.0.6.jar:?]
		... 15 more

**Comment by kjchiamu** [comment]
Was able to run the following command, and the server stopped crashing.

/kill @e[type=rats:rat]

That killed all of the rats, including the one that was crashing the server.
