### ISSUE TITLE
Game keeps crashing when loading saved world.

### ISSUE THREAD

**Issue by Furious1964** [AllTheMods/ATM-6#866]
I keep getting this error and I don't know how to solve it. Running the latest version (ATM6 1.4.0). Can anyone help me?

java.lang.NoSuchMethodError: net.minecraft.world.server.ChunkManager$ProxyTicketManager.shouldForceTicks(J)Z
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProvider.java:356) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$31523/117097536.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$30533/364328924.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by xqawas** [comment]
Same for me. worked fine in 1.3.9b

**Comment by boostmeister98** [comment]
Mine is crashing as well, but I get the error output, that the create:waterwheel is causing the crash, and after removing them with NBT editor I get no crashes

**Comment by xqawas** [comment]
I have a water wheel next to my log out point, can you tell me how to remove it? i have never used NBT Editor 

> Mine is crashing as well, but I get the error output, that the create:waterwheel is causing the crash, and after removing them with NBT editor I get no crashes

**Comment by Furious1964** [comment]
Don't have waterwheel, it crashed on a new world.

**Comment by Furious1964** [comment]
Is it possible to revert back to 1.3.9b without having to delete the pack?

**Comment by xqawas** [comment]
I don't know. But i stopped crashing after updating optifine, i used optifine HD U G5 on 1.3.9b and now i updated to optifine U G6 PRE12 and can load my world just fine, but you said it was a new world. so thats weird

**Comment by Furious1964** [comment]
Already have that version.

**Comment by Furious1964** [comment]
Nope, still get the same ticking error when going to 1.4.0.
