### ISSUE TITLE
Server crashed and thrown ClassNotFoundException: com.google.common.collect.ImmutableList

### ISSUE THREAD

**Issue by Remering** [AllTheMods/ATM-6#879]
**Describe the bug**
ClassNotFoundException: com.google.common.collect.ImmutableList 
**To Reproduce**
1. Download modpack "All the mods 6“ server files from [curseforge](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/).
 2. Extract.
 3. Open `startserver.bat` in my favourite terminal.
 4. Take a shower while waiting for downloading.
 5. Confirm and accept the eula.
 6. `ClassNotFoundException` was thrown and server crashed.

**Additional context**
```
INFO: Checking java installation...

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)

INFO: Found 64-bit Java 1.8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[16:00:41] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[16:00:41] [INFO]    Minecraft-Forge Server install/launcher jar
[16:00:41] [INFO]    (Created by the "All The Mods" modpack team)
[16:00:41] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[16:00:41] [INFO]
[16:00:41] [INFO]    This jar will launch a Minecraft Forge Modded server
[16:00:41] [INFO]
[16:00:41] [INFO]    Github:    https://github.com/AllTheMods/ServerStarter
[16:00:41] [INFO]    Discord:   http://discord.allthepacks.com
[16:00:41] [INFO]
[16:00:41] [INFO] You are playing All the Mods 6
[16:00:41] [INFO] Starting to install/launch the server, lean back!
[16:00:41] [INFO] ::::::::::::::::::::::::::::::::::::::::::::::::::::
[16:00:41] [INFO]
[16:00:41] [INFO] Pinging 8.8.8.8.
[16:00:42] [INFO] Reached 8.8.8.8: true
[16:00:42] [INFO] Pinging 1.1.1.1.
[16:00:42] [INFO] Reached 1.1.1.1: true
[16:00:42] [INFO] Reached 2 out of 2 IPs.
[16:00:42] [INFO] Server is already installed to correct version, to force install delete the serverstarter.lock File.
[16:00:42] [INFO] Starting Forge, output incoming
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
2021-01-17 16:00:42,987 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2021-01-17 16:00:43,029 main WARN Advanced terminal features are not available in this environment
2021-01-17 16:00:43,105 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[16:00:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 35.1.37, --fml.mcpVersion, 20201102.104115, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, nogui]
[16:00:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_271 by Oracle Corporation
[16:00:43] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
Exception in thread "main" [16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.mixin.MixinEnvironment$Phase.<clinit>(MixinEnvironment.java:99)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.service.MixinServiceAbstract.getInitialPhase(MixinServiceAbstract.java:87)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:141)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:84)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap$Values.forEach(Unknown Source)
formationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.net.URLClassLoader.findClass(Unknown Source)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[16:00:43] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         ... 14 more
[16:00:43] [INFO] Server has been stopped, it has started 1 times in 60min
[16:00:43] [INFO] Restarting server in 10 seconds, press ctrl+c to stop
Terminate batch job (Y/N)? Y
```
**My trials to solve it**
 1. Add `-cp` option 
 2. Reinstall the full modpack by deleting `serverstarter.lock`
 3. Reinstall forge 
 4. Replace `libraries` folder with my client one.(My client can open successfully)
 5. Upgrade the forge version to `35.1.37`

**Comment by Remering** [comment]
reinstall forge `35.1.36`

**Comment by monik3r** [comment]
Having this happen with 1.7.8. It's fixed by setting 
```  loaderVersion: 36.2.0``` in the server-setup-config.yml. Newer versions of forge have the same issue popping up again.
