### ISSUE TITLE
server crash ATM6/1.5.0 in the "other"

### ISSUE THREAD

**Issue by dextris2** [AllTheMods/ATM-6#988]
ATM6/1.5.0
Crashing server wile walking in the other. I have disabled the pix village and still crashing

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 1/31/21 1:13 PM
Description: Feature placement

java.lang.RuntimeException: We are asking a region for a chunk out of bound | -42 143
	at net.minecraft.world.gen.WorldGenRegion.func_217353_a(WorldGenRegion.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.WorldGenRegion.func_212866_a_(WorldGenRegion.java:106) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.WorldGenRegion.func_201676_a(WorldGenRegion.java:322) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IWorldReader.func_205770_a(IWorldReader.java:67) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IBiomeReader.func_205770_a(SourceFile:32) ~[?:?] {re:mixin,re:classloading}
	at com.github.alexthe666.iceandfire.world.gen.WorldGenPixieVillage.func_241855_a(WorldGenPixieVillage.java:52) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.world.gen.WorldGenPixieVillage.func_241855_a(WorldGenPixieVillage.java:26) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chocolate.mixins.json:world.biome.BiomeMixin,pl:mixin:APP:ftbchunks.mixins.json:BiomeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

**Comment by Letoric** [comment]
Looks to me like you did not disable it, based on the error you're showing. The recommendation is to set the size to 5, from 25, and that has resolved the crash for others.
